# Generated by Django 2.0.7 on 2018-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
