# Generated by Django 2.0.7 on 2018-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
